"""Add source_state

Revision ID: 093875a2c7ba
Revises: 85f2243c00d3
Create Date: 2025-03-01 10:22:57.668281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '093875a2c7ba'
down_revision: Union[str, None] = '85f2243c00d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_rag_sources',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='Telegram user ID'),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['rag_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('active_rag_sources')
    # ### end Alembic commands ###
