"""Initial migration

Revision ID: 85f2243c00d3
Revises: 
Create Date: 2025-03-01 05:55:50.399437

"""
from typing import Sequence, Union

import pgvector
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85f2243c00d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_sources',
    sa.Column('name', sa.String(), nullable=False, comment='Source name (from filename)'),
    sa.Column('source_type', sa.String(), nullable=False, comment='Type of source (pdf, txt, doc, etc)'),
    sa.Column('index_status', sa.String(), nullable=False, comment='Indexing status'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='Telegram user ID'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('embeddings',
    sa.Column('text_chunk', sa.Text(), nullable=False, comment='Text chunk'),
    sa.Column('vector_512', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False, comment='Embedding vector (512 dimensions)'),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['rag_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('embeddings')
    op.drop_table('rag_sources')
    # ### end Alembic commands ###
